name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version for the build to be released'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: generate tag and release body
      #   run: |
      #     git config --global user.name "Greator"
      #     git config --global user.email "devops@greator.com"
      #     npx standard-version -t "" -i RELEASE_BODY.md --header "# Changelog" --release-as ${{ github.event.inputs.releaseVersion }} --skip.commit
      # - name: publish tag
      #   id: publish_tag
      #   run: |
      #     git push --follow-tags
      #     echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
      # - name: create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
      #     tag_name: ${{ steps.publish_tag.outputs.tag_name }}
      #     body_path: RELEASE_BODY.md
      - name: bump android version in bitrise config
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: "ANDROID_VERSION_NAME: '.*-alpha.*"
          replace: "ANDROID_VERSION_NAME: \"'${{ github.event.inputs.releaseVersion }}-alpha'\""
          include: "bitrise.yml"
      - name: bump ios version in bitrise config
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: "IOS_VERSION_NUMBER: .*-alpha"
          replace: "IOS_VERSION_NUMBER: ${{ github.event.inputs.releaseVersion }}-alpha"
          include: "bitrise.yml"
      - name: bump version in gradle.properties
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: "APP_VERSION_NUMBER=.*-alpha"
          replace: "APP_VERSION_NUMBER=${{ github.event.inputs.releaseVersion }}-alpha"
          include: "android/gradle.properties"
      - name: bump marketing version iOS project file
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: "MARKETING_VERSION = .*-alpha;"
          replace: "MARKETING_VERSION = ${{ github.event.inputs.releaseVersion }}-alpha;"
          include: "ios/AppName.xcodeproj/project.pbxproj"
      - name: testing output
        run: |
          cat bitrise.yml
          cat android/gradle.properties
          cat ios/AppName.xcodeproj/project.pbxproj
      - name: create version bump PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(release): bump version numbers post-release"
          branch: post-release-version-bump
          base: master
